# These are supported funding model platforms

# bitcoin
bc1q04zs40e9cakxuu2lw3r04jc2vmmv084rvz5kx9
# usdt (TRON)
TDmZvrFGBKyP9opEL1FCzpvH9MXBmJ9r6q
# ethereum
0x139aB14D67B1E0dAaEDe1CF5e3234B1Cc3644BE0

# github: [user1, user2]
# patreon: user
# open_collective: username
# ko_fi: username
# tidelift: platform-name/package-name
# lfm: username
# buy_me_a_coffee: username
# issuehunt: username
# otechie: username
# custom: ['https://example.com']
